# Generated by Django 5.0.6 on 2024-06-06 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='Unisex', max_length=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('haggle', models.CharField(choices=[('Negotiable', 'Negotiable'), ('Unnegotiable', 'Unnegotiable')], default='Negotiable', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='image/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='core.categorie')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fashion_vendors', to='user.vendor')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
