# Generated by Django 5.0.6 on 2024-06-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_vendor_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='business_whatsapp_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
